### ISSUE TITLE
Specification for reboot required notifications

### ISSUE THREAD

**Issue by julian-klode** [uapi-group/specifications#41]
Various things can cause a system to need to be rebooted.

* new OS images (or new kernels for package-based, um, compartmentalized OS [maybe you deliver kernels in separate images than your userspace image...])
* firmware updates

It appears we do not have a common way to surface that a reboot is required to users, and should probably work on one. This needs to be persistent for the boot: If a user logs in and a reboot is required, they should know about that, it should not only be notified to users when the upgrade was installed.

*Individual* reboot required reasons should be inhibitable. For example, consider you are upgrading a kernel only but your kernel is also being patched live at run time, you don't want to reboot in that case as the security hole is fixed. You still want to get the notification if there are other reasons, though. The live patching could have happened before or after the kernel upgrade. One way to solve this would be to have cancellable reboot reasons, and then the kernel upgrade can check if the running kernel was already patched before issuing a "reboot required" and the live patch if it runs later could "cancel" the "reboot required" from the kernel.

You also want to inhibit notifications totally while something else is running, so you don't end up in the awkward place where you suggest a reboot and then you can't reboot, but the notification could just be hidden while something is inhibiting reboots.

This points to another interesting problem: We should differentiate between security reboots and bug fix reboots. If your system needs a reboot for security reasons, you might want to carry it out ASAP, but if it works fine and it's just bug fixes, you might want to hold off. To generalize this, we should talk about "critical" or "urgent" reboots and "normal" ones.

Prior art:

* In the classic Debian and Ubuntu world, we use an empty file /run/reboot-required to signal that an update is required, and a file /run/reboot-required.pkgs to list the packages that caused that. (I'd have to stay compatible with that by pushing any info back into that of course).
* If ChromeOS has a pending upgrade to be activated by reboot, it shows a persistent notification and gives you a nice logo (that's like where I'd want GNOME to end up with).

**Comment by bluca** [comment]
We have the inhibitors system, should hook up into that I guess?

**Comment by julian-klode** [comment]
I think it's fairly similar to inhibitors in that you have a who, what, why; but instead of just inhibitors you also have - for lack of better word - exhibitors. Like not just inhibit reboots, but also suggest reboots.

> You need to reboot because <fwupd> <prepared firmware updates>

**Comment by pothos** [comment]
On Flatcar (inherited by CoreOS CL) we use a special file that gets sourced on login to notify the user: https://github.com/flatcar/baselayout/blob/flatcar-master/baselayout/flatcar-profile.sh#L18

**Comment by lnussel** [comment]
the [shutdown(8)](https://www.freedesktop.org/software/systemd/man/shutdown.html) command allows to specify a custom message when scheduling shutdowns. So far there's no dbus event when it gets set though, only logging to the journal (https://github.com/systemd/systemd/pull/23870).
It is possible to query dbus properties to check whether a reboot is scheduled though. So desktops could show an icon or something signalling a pending reboot to users.

Instead of just setting a flag that signals reboot required that then may never actually take place MicroOS defines a maintenance window by default. So if a reboot is needed it will be scheduled at night. It's still possible to cancel or move the time using the `shutdown` command of course. I've proposed adding the feature to systemd here: https://github.com/systemd/systemd/pull/25049

An interesting case for desktops might be to test what happens when the system is sent to sleep before a scheduled is actually performed.

**Comment by bluca** [comment]
Yes we could use that - in general, the `login1` interface on the system bus already provides extensive functionality relative to shutdown/reboots, scheduling them, blocking them, notifications and so on. There are signals and properties. So it makes sense to add a new interface for this, if needed, as it seems largely a small variations of existing functionality.

**Comment by Ijlal-loutfi** [comment]
Capturing the concept of "critical" or "urgent" reboots and "normal" ones would be useful for livepatch for instance. We would like to express the notion of a recommended reboot, when w new kernel is available, but we are nonetheless still live patching their current kernel for critical/high CVEs. Do you have already an idea on how we can express these different levels of reboot severity levels, while remaining compatible with Debian file systems approach?

**Comment by julian-klode** [comment]
The Debian approach is a bit out of scope, but suffice it to say clients would migrate to logind to read pending reboots and alert.

And for the Debian approach, well apt would after a run do the dbus calling to logind if there was anything not yet scheduled.

**Comment by julian-klode** [comment]
Can we transfer this to systemd/systemd or does it need closing and new bug?

**Comment by julian-klode** [comment]
Moved to https://github.com/systemd/systemd/issues/26200
