### ISSUE TITLE
Drop-ins should not be mandatory

### ISSUE THREAD

**Issue by janc13** [uapi-group/specifications#48]
From the Base Directory Specification:

> All configuration paths must support drop-ins. Supporting drop-ins means that in addition to parsing $XDG_CONFIG_DIRS/foo/bar, an implementation also must parse all files in $XDG_CONFIG_DIRS/foo/bar.d/, and merge the result in lexicographic order. 

While drop-in directories are a good idea for many applications (e.g. for integration of multiple applications & to facilitate package upgrades), some configuration file formats can’t be merged, or (unstructured) merging might not be desirable (e.g. for security reasons, or because it adds too much complications), so the specification should not make that mandatory. Recommending that it should be implemented where possible/desirable would make more sense.

**Comment by aplanas** [comment]
Do you have an example for such configuration system, where drop-ins cannot be added (not that they are not implemented) or desirable?

Some complex one like Apache are supporting this, and some security sensitive ones like ssh also. I am sure that you are right, and I am interested to know such examples.

On the other side the BDS rationale has the advantage that the configuration files can be split into what the service provider deploy as a default (that can be written in a read-only part of the system) and the drops-in that the admin can provide for the specifics of the service (stored in a different read-write part of the system).

A package update for the service will update this fixed part that is in the RO, improving the security defaults, but still accepting the user overwrites and merging them on the running service.

**Comment by janc13** [comment]
SSH _optionally_ implements this. By default the main `/etc/ssh/ssh_config` & `/etc/ssh/sshd_config` files in most (but maybe not all?) distros include files in `/etc/ssh/ssh_config.d/*.conf` & `/etc/ssh/sshd_config.d/*.conf` respectively at the start of that file, but it’s up to whomever admins the main configuration files whether to allow/implement the directories or not, and I wouldn’t be surprised if some admins remove those includes so that no other package can make “surprise changes” to their SSH configuration…

But there are also applications that use object dumps or database files (e.g. SQLite) or script includes, or something else that doesn’t resemble a simple “key-value store” to store configuration data, and it could be quite complicated (if possible at all) to implement `*.d/` directories for these.

And even when it would be possible, it might not be worth the trouble for some applications, e.g. when the application is otherwise very simple, and isn’t designed to be integrated with other packages (so there is no need).

BTW: based on the rest of the spec, a package can put its default, read-only configuration in a different read-only location (e.g. `/usr/etc/`), so there is no real need for the drop-in subdirectories to be able to override that. And for desktop applications that run as a regular user there is even less need…

**Comment by keszybz** [comment]
> SSH _optionally_ implements this.

FWIW, I think that this is actually a good *counter*example. If some systems support `/etc/ssh/ssh_config.d/*.conf` and some don't, we get unpredictability and user frustration. So we're just better off if .d support is present.

> But there are also applications that use object dumps or database files

Yeah. I think we should qualify the requirement: "All configuration paths must support drop-ins. [...] **This requirement does not apply to configuration file formats where automatic combining of multiple files is not feasible, for example scripts or structured documents.**". Suggestions about wording welcome.
