### ISSUE TITLE
boot_loader_specification: Broken anchor links

### ISSUE THREAD

**Issue by a3f** [uapi-group/specifications#63]
https://uapi-group.org/specifications/specs/boot_loader_specification/ has a number of links that should point at anchors within the site, e.g.:

> increasing [alphanumerical order](https://uapi-group.org/specifications/#alphanumerical-order)), machine-id (A-Z, increasing alphanumerical order), and version keys (decreasing [version order](https://uapi-group.org/specifications/#version-order)).

But instead of pointing at the same document, they point at https://uapi-group.org/specifications which has no such anchors.

**Comment by mrc0mmand** [comment]
Unfortunately, this seems to break other relative links, like `[Version Format Specification](specs/version_format_specification.md)`, which is now not translated to `specs/discoverable_disk_image/`, wonderful.

**Comment by mrc0mmand** [comment]
Ah, so another solution seems to be using the `relref` hugo feature, i.e. instead of

```
[alphanumerical order](#alphanumerical-order)
```

using

```
[alphanumerical order]({{< relref "#alphanumerical-order" >}})
```

which seems to DTRT as far as I can see. It's not particularly pretty, but given we have only a handful of anchors, it might be a viable option.
```

**Comment by mrc0mmand** [comment]
And to wrap this up, the portable links stuff was introduced in 4cd8de06dbee1411e99167d923fd7c1c21e09f8c, which also converted the relative links to their current form. So I guess using `relref`[0] might be the easier way out here.

[0] https://gohugobrasil.netlify.app/content-management/cross-references/
