### ISSUE TITLE
UKI specification: support multiple embedded device trees

### ISSUE THREAD

**Issue by diogo-ivo** [uapi-group/specifications#66]
Currently the UKI specification states that there can be one .dtb section where a Device Tree is placed. However, there are use cases where it is useful for one UKI to contain multiple DTs, allowing a single image to support multiple (similar) boards. As such, it would be good to see if there is interest in standardizing this feature.

An initial proposal for this is as follows:

- The extra FDTs are embedded in the UKI by adding sections named .dtb-* for each additional Device Tree (this is already implemented in efibootguard). Another solution would be to concatenate the FDTs in the same .dtb section (with possible appropriate padding), but this raises some problems with maintaining backwards compatibility.
- The selection of the appropriate FDT is done by matching the compatible strings against the firmware provided FDT

**Comment by bluca** [comment]
Yes we want to support this, it needs to be implemented in sd-stub at the same time though

**Comment by jan-kiszka** [comment]
To be clear: Ivo would also contribute the needed code changes to sd-stub. He already has a working prototype, just not yet exactly with the suggested format above.

**Comment by poettering** [comment]
I guess we can close this here, now that #71 has been merged.

(Would have preferred if we merge the systemd PR and this spec PR at the same time, but I guess that ship has sailed)
