### ISSUE TITLE
DDI specification doesn't guarantee a stable mountpoint for the ESP partition

### ISSUE THREAD

**Issue by DaanDeMeyer** [uapi-group/specifications#67]
It's a very nice property to have the ESP partition guaranteed to be mounted at a stable location if it's available. Currently it can either be mounted at /boot or at /efi depending on what partitions are available inside the image and whether there are files in /boot inside the image. This requires tools that want to run an operation on the ESP to implement complicated logic to figure out whether the ESP is mounted at /boot or whether it is mounted at /efi. Ideally we would guarantee that the ESP is mounted at /efi to make it easier for tools to operate on the ESP of a mounted image.

**Comment by keszybz** [comment]
C.f. #35.

**Comment by keszybz** [comment]
I think we will just have to accept this. Writing of a boot manager is a fairly complex and specialized operation. With the changes in #75, I think we have logic that is easy to describe and understand, and new **kernels** go to `/boot` in all scenarios. Where the **boot loader** goes is more complicated, but I think this a much more specialized thing and we don't need to optimize for that.

**Comment by AdrianVovk** [comment]
The other option is to just always bind-mount /boot to /efi if the ESP is being used as $BOOT. Or, the other way around: always mount the ESP to /efi, then bind-mount it over /boot if necessary.

That way, the ESP is always available at /efi, then $BOOT is always available at /boot
